wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.7
    start_time: 1681135129.666926
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 17
      - 19
      - 23
      - 37
      4: 3.10.7
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
